

apiVersion: v1
kind: Service
metadata:
  name: wordpress-east
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: wordpress-east
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: wordpress-east
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-east
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress-east
        tier: frontend
    spec:
      containers:
      - name: wordpress-east
        image: tutum/wordpress
        resources:
          requests:
            cpu: 100m
            memory: 1000Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 80