
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: wordpress
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: wordpress
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-11-25T01:46:55Z
  generation: 1
  labels:
    app: wordpress
  name: wordpress
  namespace: wpname
  resourceVersion: "2007"
  selfLink: /apis/extensions/v1beta1/namespaces/wpns/deployments/wordpress
  uid: fd36bfaf-f053-11e8-b14c-42010a8a00b6
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordpress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      containers:
      - image: tutum/wordpress
        imagePullPolicy: Always
        name: wordpress
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: 2018-11-25T01:47:22Z
    lastUpdateTime: 2018-11-25T01:47:22Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-11-25T01:46:55Z
    lastUpdateTime: 2018-11-25T01:47:23Z
    message: ReplicaSet "wordpress-575b56c459" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
